services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - "80:3000"
    command: "${API_COMMAND}"
    restart: "${RESTART_POLICY-no}"
  database:
    image: "postgres:13.5"
    ports:
    - "5433:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    restart: "${RESTART_POLICY-no}"
  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: "${RESTART_POLICY-no}"

volumes:
  postgres-data: {}


