{{ if .Values.background.backend.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env }}-backend-configmap
data:
  FRONT_URL: "http://{{ .Values.env }}-frontend-service:{{ .Values.background.frontend.externalPort }}"
---
{{ end }}