{{ if .Values.background.backend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-backend-deployment
  labels:
    app: {{ .Values.env }}-backend
spec:
  replicas: {{ .Values.background.backend.replica }}
  selector:
    matchLabels:
      app: {{ .Values.env }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-backend
    spec:
      containers:
        - name: {{ .Values.env }}-backend
          image: {{ .Values.background.backend.image }}
          imagePullPolicy: {{ .Values.background.backend.pullPolicy }}
          command: ["/bin/sh","-c"]
          args: ["npx prisma generate && npm start"]
          ports:
            - containerPort: {{ .Values.background.backend.internalPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.env }}-backend-secret

---
{{ end }}