{{ if .Values.background.backend.enabled }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.env }}-backend-secret
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGRldi1wb3N0Z3Jlc3FsLXNlcnZpY2U6NTQzMi9iYWNrZ3JvdW5k"
---
{{ end }}