{{ if .Values.background.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.env }}-backend
  name: {{ .Values.env }}-backend-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.env }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.background.backend.externalPort }}
      targetPort: {{ .Values.background.backend.internalPort }}
---
{{ end }}