apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: background-dev
    meta.helm.sh/release-namespace: backend-team
  creationTimestamp: "2023-10-09T12:13:01Z"
  labels:
    app.kubernetes.io/instance: background-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: adminer
    helm.sh/chart: adminer-0.2.1
  name: background-dev-adminer
  namespace: backend-team
  resourceVersion: "853180883"
  uid: 2ae49742-3e60-4c69-aae1-8f0aa092ef18
spec:
  clusterIP: 10.3.152.225
  clusterIPs:
  - 10.3.152.225
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30063
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: background-dev
    app.kubernetes.io/name: adminer
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
