env: dev

background:
  frontend:
    enabled: true
    image: lucasdsm78/background-front:latest
    pullPolicy: Always
    internalPort: 3000
    externalPort: 8080
    replica: 1
  backend:
    enabled: true
    image: anisbastide/background_back:latest
    pullPolicy: Always
    internalPort: 3000
    externalPort: 3000
    replica: 1
  postgresql:
    image: postgres:16-alpine
    pullPolicy: Always
    storage: 512Mi
    internalPort: 5432
    externalPort: 5432
    replica: 1
  ingress:
    enabled: false

route:
  domain: "leaddev.digitalseeder.com"

imagePullSecrets: []