{{ if .Values.background.backend.enabled }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.env }}-postgresql-secret
data:
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="
  POSTGRES_DB: "YmFja2dyb3VuZA=="
---
{{ end }}