{{ if .Values.deployment.backend }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.env }}-postgresql-secret
data:
  DB_NAME: {{ "background" | b64enc }}
  DB_PASSWORD: {{ "1234" | b64enc }}
  DB_USER: {{ "user" | b64enc }}
  DB_HOST: {{ "database" | b64enc }}
  DB_PORT: {{ "5432" | b64enc }}
---
{{ end }}