{{ if .Values.deployment.backend }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.env }}-postgresql
  name: {{ .Values.env }}-postgresql-service
spec:
  selector:
    app: {{ .Values.env }}-postgresql
  ports:
      - protocol: TCP
        port: {{ .Values.background.postgresql.port }}
        targetPort: 5432
---
{{ end }}