{{ if .Values.background.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.env }}-postgresql
  name: {{ .Values.env }}-postgresql-service
spec:
  selector:
    app: {{ .Values.env }}-postgresql
  ports:
      - protocol: TCP
        port: {{ .Values.background.postgresql.externalPort }}
        targetPort: {{ .Values.background.postgresql.internalPort }}
---
{{ end }}