{{ if .Values.background.frontend.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env }}-frontend-configmap
data:
  REACT_APP_BACKEND_URL: "http://{{ .Values.route.domain }}/"
  #REACT_APP_BACKEND_URL: "http://{{ .Values.env }}-backend-service:{{ .Values.background.backend.externalPort }}/"
---
{{ end }}