{{ if .Values.background.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.env }}-frontend
  name: {{ .Values.env }}-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.env }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.background.frontend.externalPort }}
      targetPort: {{ .Values.background.frontend.internalPort }}
---
{{ end }}